name: Process Videos from Dropbox

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # This action downloads your repository code, including fixed-python-script.py
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        # Install dropbox, google.generativeai, and markdown
        run: |
          python -m pip install --upgrade pip
          pip install dropbox google.generativeai markdown

      # --- Removed: Download processed files state (artifact logic) ---
      # - name: Download processed files state
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: processed-files-state
      #     path: .

      # --- Removed: Create service account key file (Google Drive specific) ---
      # - name: Create service account key file
      #   run: |
      #     echo '${{ secrets.GOOGLE_CREDENTIALS }}' > service-account.json

      # --- Removed: Create combined processing script (uses external file now) ---
      # - name: Create combined processing script
      #   run: |
      #     cat > process_and_upload.py << 'EOF'
      #     ...
      #     EOF

      - name: Run the processing script
        # Execute the external Python script file
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }} # Pass the Dropbox secret
        run: python fixed-python-script.py # <-- Execute the external file

      # --- Removed: Upload updated processed files state (artifact logic) ---
      # - name: Upload processed files state
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: processed-files-state
      #     path: processed_files.json
      #     retention-days: 7
